In [1]:
!pip install pandas scikit-learn transformers torch datasets
!pip install -U transformers

Requirement already satisfied: pandas in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.3)
Requirement already satisfied: scikit-learn in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.9.0)
Requirement already satisfied: transformers in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (5.11.0)
Requirement already satisfied: torch in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.12.0)
Requirement already satisfied: datasets in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (5.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (1.18.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (4.68.2)
Requirement already satisfied: click>=8.4.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.3.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: setuptools<82 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: xxhash in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: colorama in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: six>=1.5 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: transformers in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (5.11.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (1.18.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers) (4.68.2)
Requirement already satisfied: click>=8.4.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.3.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: colorama in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [2]:
import pandas as pd

df = pd.read_csv("support_tickets.csv")
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [3]:
df = df[["Ticket Description", "Ticket Type"]]
df = df.dropna()
df = df.sample(100, random_state=42)
df.head()

                                     Ticket Description      Ticket Type
4830  I'm having an issue with the {product_purchase...   Refund request
7075  I'm having trouble connecting my {product_purc...  Product inquiry
4715  I'm having an issue with the {product_purchase...  Billing inquiry
2022  I'm having an issue with the {product_purchase...  Billing inquiry
676   I'm having an issue with the {product_purchase...   Refund request

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df["Ticket Description"],
    df["Ticket Type"],
    test_size=0.2,
    random_state=42
)

In [5]:
from transformers import pipeline

zero_shot = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

labels = df["Ticket Type"].unique().tolist()

C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 515/515 [00:00<00:00, 2302.95it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [6]:
def zero_shot_predict(text):
    result = zero_shot(text, labels)

    top3 = sorted(
        zip(result["labels"], result["scores"]),
        key=lambda x: x[1],
        reverse=True
    )[:3]

    return top3

In [7]:
def few_shot_prompt(text):
    return f"""
Example:
Ticket: Internet not working
Tag: Technical Issue

Example:
Ticket: Refund not received
Tag: Billing Issue

Now classify:
Ticket: {text}
Tag:
"""

In [8]:
for text in X_test.iloc[:10]:
    print("Ticket:", text)
    print("Top 3 Tags:", zero_shot_predict(text))
    print("-" * 50)

Ticket: I'm having an issue with the {product_purchased}. Please assist.

Q8. When should the new products use the brand? Ashbrook has a range of new products, but the new products aren't that common? I've already contacted customer support multiple times, but the issue remains unresolved.
Top 3 Tags: [('Product inquiry', 0.6829251646995544), ('Billing inquiry', 0.12988929450511932), ('Technical issue', 0.108836330473423)]
--------------------------------------------------
Ticket: I've encountered a data loss issue with my {product_purchased}. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? Thanks! I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.
Top 3 Tags: [('Product inquiry', 0.6075623035430908), ('Technical issue', 0.1780497133731842), ('Billing inquiry', 0.08944873511791229)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist.

Solutions

Cake and Basket, The Whole Meal:

You don't need to be concerned about your eggs being in shape and tasting I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?
Top 3 Tags: [('Product inquiry', 0.7162684202194214), ('Technical issue', 0.17085713148117065), ('Billing inquiry', 0.07889434695243835)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist. - Please also help me with further problems like the {productID} has been changed.

I'm having an issue with the {product_purchased I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?
Top 3 Tags: [('Product inquiry', 0.6093764305114746), ('Technical issue', 0.1701410561800003), ('Billing inquiry', 0.1128154993057251)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist.

My question?

Does the Product Purchase Policy address the current availability (if at all) of the product we provide?

Please see the FAQ I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?
Top 3 Tags: [('Product inquiry', 0.6407397985458374), ('Technical issue', 0.19667665660381317), ('Billing inquiry', 0.09061489999294281)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist.

"Products that have been purchased at that time are now out of stock. Thank you for your support. The {product_purchased} will get I'm using the original charger that came with my {product_purchased}, but it's not charging properly.
Top 3 Tags: [('Product inquiry', 0.5727837681770325), ('Billing inquiry', 0.177128404378891), ('Technical issue', 0.11706400662660599)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist.

* Update, delete, or delete this item

This Item is discontinued, or no longer available.

Please help us keep the order order current I need assistance as soon as possible because it's affecting my work and productivity.
Top 3 Tags: [('Product inquiry', 0.7120102047920227), ('Technical issue', 0.1103898286819458), ('Cancellation request', 0.08494838327169418)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist.


<div>

<p><strong>No. Product Purchased: No


<strong>Price Paid: $9.99 I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.
Top 3 Tags: [('Product inquiry', 0.7921642661094666), ('Technical issue', 0.10354597866535187), ('Billing inquiry', 0.04529525339603424)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist. Your product has now shipped to us and the seller agreed to ship to your address for you to use. Thank you


Shipping

We believe you will ship I've tried clearing the cache and data for the {product_purchased} app, but the issue persists.
Top 3 Tags: [('Product inquiry', 0.4762144386768341), ('Technical issue', 0.2824150621891022), ('Billing inquiry', 0.11388865858316422)]
--------------------------------------------------
Ticket: I'm having an issue with the {product_purchased}. Please assist. I'm using xda-developer for something different. If there are issues with the {product_purchased} it's likely you are not using the I've tried clearing the cache and data for the {product_purchased} app, but the issue persists.
Top 3 Tags: [('Product inquiry', 0.3974139392375946), ('Technical issue', 0.3893178701400757), ('Cancellation request', 0.08012238144874573)]
--------------------------------------------------

In [9]:
from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

In [10]:
def tokenize(batch):
    return tokenizer(batch, truncation=True, padding=True)

train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=128
)

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

In [12]:
import torch

class TicketDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = TicketDataset(train_encodings, y_train_enc)
test_dataset = TicketDataset(test_encodings, y_test_enc)

In [13]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(le.classes_)
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1603.71it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [14]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=2,
    per_device_train_batch_size=16
)

In [15]:
import numpy as np
from sklearn.metrics import accuracy_score

def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    return {"accuracy": accuracy_score(p.label_ids, preds)}

In [16]:
from transformers import Trainer, TrainingArguments
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

C:\Users\M A D I N A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.49s/it]

TrainOutput(global_step=10, training_loss=1.611007308959961, metrics={'train_runtime': 90.2117, 'train_samples_per_second': 1.774, 'train_steps_per_second': 0.111, 'total_flos': 3725844912000.0, 'train_loss': 1.611007308959961, 'epoch': 2.0})

In [17]:
def fine_tuned_predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    outputs = model(**inputs)
    pred = outputs.logits.argmax().item()
    return le.inverse_transform([pred])[0]

In [18]:
sample = X_test.iloc[0]

print("TEXT:", sample)
print("ZERO-SHOT:", zero_shot_predict(sample))
print("FINE-TUNED:", fine_tuned_predict(sample))

TEXT: I'm having an issue with the {product_purchased}. Please assist.

Q8. When should the new products use the brand? Ashbrook has a range of new products, but the new products aren't that common? I've already contacted customer support multiple times, but the issue remains unresolved.
ZERO-SHOT: [('Product inquiry', 0.6829251646995544), ('Billing inquiry', 0.12988929450511932), ('Technical issue', 0.108836330473423)]
FINE-TUNED: Refund request

In [19]:
def top3_tags(text):
    result = zero_shot(text, labels)

    top3 = sorted(
        zip(result["labels"], result["scores"]),
        key=lambda x: x[1],
        reverse=True
    )[:3]

    return top3
df_small = df.sample(min(100, len(df)), random_state=42)

df_small["Top3 Tags"] = df_small["Ticket Description"].apply(top3_tags)

df_small.head()

,Ticket Description,Ticket Type,Top3 Tags
3684,I'm having an issue with the {product_purchase...,Cancellation request,"[(Product inquiry, 0.6829251646995544), (Billi..."
1090,I've encountered a data loss issue with my {pr...,Technical issue,"[(Product inquiry, 0.6075623035430908), (Techn..."
5141,I'm having an issue with the {product_purchase...,Product inquiry,"[(Product inquiry, 0.7162684202194214), (Techn..."
2812,I'm having an issue with the {product_purchase...,Refund request,"[(Product inquiry, 0.6093764305114746), (Techn..."
7307,I'm having an issue with the {product_purchase...,Cancellation request,"[(Product inquiry, 0.6407397985458374), (Techn..."